#!/usr/bin/env python3
"""Cut a release of either the code or the data, never both in one call.

  tools/release.py code <major|minor|patch> "message"
  tools/release.py data <major|minor|patch> "message"

Code version lives in VERSION and CHANGELOG.code.md; tag `code-vX.Y.Z`.
Data version lives in data/agentic-model-timeline.json (data_version and the
changelog array); tag `data-vX.Y.Z`. CHANGELOG.data.md is regenerated by build.

Run through `make release-code` / `make release-data`, which build and test first.
The script refuses to run on a dirty tree outside the files it owns, so a data
release cannot silently carry a code change and vice versa.
"""
import datetime
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "agentic-model-timeline.json"

OWNED = {
    "code": {"VERSION", "CHANGELOG.code.md", "src/", "tools/", "test/", "prompt/",
             "Makefile", "Dockerfile", "package.json", "package-lock.json", "README.md", ".gitignore"},
    "data": {"data/", "CHANGELOG.data.md"},
}


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, check=True,
                          capture_output=True, text=True).stdout.strip()


def bump(v: str, part: str) -> str:
    ma, mi, pa = (int(x) for x in v.split("."))
    if part == "major":
        return f"{ma + 1}.0.0"
    if part == "minor":
        return f"{ma}.{mi + 1}.0"
    if part == "patch":
        return f"{ma}.{mi}.{pa + 1}"
    raise SystemExit(f"unknown bump '{part}'")


def changed_paths() -> list[str]:
    # -z: NUL-separated, no quoting, and no whole-output strip that would eat
    # the leading status column of the first entry.
    out = subprocess.run(["git", "status", "--porcelain", "-z", "--untracked-files=all"],
                         cwd=ROOT, check=True, capture_output=True, text=True).stdout
    return [e[3:] for e in out.split("\0") if len(e) > 3]


def owned_by(path: str, stream: str) -> bool:
    return any(path == o or (o.endswith("/") and path.startswith(o)) for o in OWNED[stream])


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__)
        return 2
    stream, part, msg = sys.argv[1], sys.argv[2], sys.argv[3].strip()
    if stream not in OWNED or not msg:
        print(__doc__)
        return 2

    foreign = [p for p in changed_paths() if not owned_by(p, stream)]
    if foreign:
        other = "data" if stream == "code" else "code"
        print(f"refusing: uncommitted changes outside the {stream} stream "
              f"(release {other} first):", *foreign, sep="\n  ", file=sys.stderr)
        return 1

    today = datetime.date.today().isoformat()
    if stream == "code":
        old = (ROOT / "VERSION").read_text().strip()
        new = bump(old, part)
        (ROOT / "VERSION").write_text(new + "\n")
        log = ROOT / "CHANGELOG.code.md"
        body = log.read_text()
        head, _, rest = body.partition("\n## ")
        log.write_text(f"{head}\n## {new} — {today}\n\n{msg}\n\n## {rest}" if rest else f"{head}\n## {new} — {today}\n\n{msg}\n")
    else:
        d = json.loads(DATA.read_text())
        old = d["data_version"]
        new = bump(old, part)
        d["data_version"] = new
        d["generated_at"] = today
        d["changelog"].append({"version": new, "date": today, "snapshot": True, "change": msg})
        DATA.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")

    subprocess.run([sys.executable, str(ROOT / "tools" / "build.py"), "build"], cwd=ROOT, check=True)
    git("add", "-A")
    git("commit", "-q", "-m", f"{stream}: v{new} — {msg}")
    git("tag", "-a", f"{stream}-v{new}", "-m", msg)
    print(f"{stream} {old} -> {new}, tagged {stream}-v{new}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
